### PR TITLE
Fix bugs and improve coding style

### PR DESCRIPTION
**Pull request by Leonana69**
Main changes:
1. In the readme, to download the dependencies, it should be `./tools/build/download_deps`
2. The `systick.h` should be included in the bootloader.c file.
3. I added -Werror cflag in the makefile, then several changes should be made:
    a) the main function has to have a return type of int, so it could not be declared as a noreturn function.
    b) in the core_cmFunc.h, there is no need to provide the name for the register in `__ASM`, the compiler says it's deprecated so I guess it's due to the old cm0 library.
4. Other changes are all about coding style.

The first two changes are essential, also if you don't want to change a lot of codes, it's fine that you make changes by yourself and close this pull request : )

### CODE REVIEW

**Comment by knmcguire** [comment]
Hi! Usually we don't accept a lot of PRs for essential parts of the crazyflie, namely the bootloader. Any issue related to this will be extremely costly.

We will need to discuss internally what to do for this, so we will come back to you with an update.

**Comment by knmcguire** [comment]
This bootloader is something that we like to keep constant in production, so for that only step 1 and 2 is necessary, but for future purposes it would be indeed good to change it so it can be used for different hardware as well. 

@krichardsson will look into this PR and perhaps ask more questions.

**Comment by Leonana69** [comment]
> This bootloader is something that we like to keep constant in production, so for that only step 1 and 2 is necessary, but for future purposes it would be indeed good to change it so it can be used for different hardware as well.
> 
> @krichardsson will look into this PR and perhaps ask more questions.

thanks for the reply!

**Comment by krichardsson** [comment]
Hi @Leonana69 !

I think it looks good, nice clean up!

As @knmcguire mentioned, we are careful when accepting pull requests for bootloaders. As all of your changes looked like styling, I wanted to see if the binary produced by the compiler for your pull request was identical to what it produces for the current master. If the binaries are identical all should be good.

I did find 3 changes in your PR that changed the binary slightly which is a bit curious:
1. including `#include "systick.h"` in bootloader.c. Perhaps the compiler is doing stuff in a different order when having the definition earlier?
2. Moving the curly brace to the same line as the function, like this `void start_firmware() {` for functions `start_firmware()` and `main()` in main.c. I don't know why that would make a difference?

Anyway I trust the compiler to do the right thing and I will merge the pull request.
Thanks!

**Pull request merged**
